### ISSUE TITLE
②トップページの表示

### ISSUE THREAD

**Issue by k-nishimoto-libertyfish** [libertyfish-co/OCA_hackathon-materials#2]
## コントロールの作成

```
rails g controller tweets
```
コントローラーにindexアクションを追加する
```ruby
  def index
    @tweets = Tweet.all
  end
```

## ルーティングの設定
`routes.rb`に以下を追加
合わせてroot_pathも設定しておきます。
```ruby
root to: 'tweets#index'
resources :tweets, only: [:index]
```

## ビュー作成
このリポジトリのapp/assetsディレクトリをそのまま受講生に配布する
`app/views/layouts/application.html.erb`
```ruby
<!DOCTYPE html>
<html>
  <head>
    <title>OCAtweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">OCATweet</a></h1>
        <div class="user_nav grid-6">
          <%= link_to  "投稿する", root_path, class: "post" %>
        </div>
      </div>
    </header>
      <%= yield %>
    <footer>
      <p>
        Copyright OCATweet 2022.
      </p>
    </footer>
  </body>
</html>
```

`app/views/tweets/index.html.erb`ファイルを作成してもらい以下をコピペ
```ruby
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <div class="content_post">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      </div>
      <div>
        <a href="/">
          <span>投稿者:</span><%= tweet.name %>
        </a>
      </div>
        <div class="tweet_text"><%= tweet.text %></div>
    </div>
  <% end %>
</div>
```

### ※画像とCSSファイルの設置
`/app/assets/stylesheets/style.css`にコメントで記述しているcssファイルをコピペで貼り付けてください。
`app/assets/images`の中に'arrow_top.png'と'user_icon.png'というふたつの画像を配置する。
※画像はcodeからダウンロードしてください！

## モデルの作成
```
rails g model tweet
```

マイグレーションファイルは以下の形
```ruby
class CreateTweets < ActiveRecord::Migration[6.0]
  def change
    create_table :tweets do |t|
      t.string :name
      t.string :text
      t.timestamps
    end
  end
end
```
→`rails db:migrate`を実行

`rails c`でコンソールを立ち上げモデルに値を追加する
```
Tweet.create(name:'山田太郎',text:'test２２２２２２')
```

ビューで確認すると見れているはず

**Comment by k-nishimoto-libertyfish** [comment]
style.css

```css
/* 全てのcssを記述している */

@charset "UTF-8";

/*! normalize.css v2.1.3 | MIT License | git.io/normalize */
/* ==========================================================================
 * HTML5 display definitions
 * ========================================================================== */
/*
 * Correct `block` display not defined in IE 8/9. */
article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
nav,
section,
summary {
  display: block;
}

/*
 * Correct `inline-block` display not defined in IE 8/9. */
audio,
canvas,
video {
  display: inline-block;
}

/*
 * Prevent modern browsers from displaying `audio` without controls.
 * Remove excess height in iOS 5 devices. */
audio:not([controls]) {
  display: none;
  height: 0;
}

/*
 * Address `[hidden]` styling not present in IE 8/9.
 * Hide the `template` element in IE, Safari, and Firefox < 22. */
[hidden],
template {
  display: none;
}

/* ==========================================================================
 * Base
 * ========================================================================== */
/*
 * 1. Set default font family to sans-serif.
 * 2. Prevent iOS text size adjust after orientation change, without disabling
 *    user zoom. */
html {
  font-family: sans-serif;
  /* 1 */
  -ms-text-size-adjust: 100%;
  /* 2 */
  -webkit-text-size-adjust: 100%;
  /* 2 */
}

/*
 * Remove default margin. */
body {
  margin: 0;
}

/* ==========================================================================
 * Links
 * ========================================================================== */
/*
 * Remove the gray background color from active links in IE 10. */
a {
  background: transparent;
}

/*
 * Address `outline` inconsistency between Chrome and other browsers. */
a:focus {
  outline: thin dotted;
}

/*
 * Improve readability when focused and also mouse hovered in all browsers. */
a:active,
a:hover {
  outline: 0;
}

/* ==========================================================================
 * Typography
 * ========================================================================== */
/*
 * Address variable `h1` font-size and margin within `section` and `article`
 * contexts in Firefox 4+, Safari 5, and Chrome. */
h1 {
  font-size: 2em;
  margin: 0.67em 0;
}

/*
 * Address styling not present in IE 8/9, Safari 5, and Chrome. */
abbr[title] {
  border-bottom: 1px dotted;
}

/*
 * Address style set to `bolder` in Firefox 4+, Safari 5, and Chrome. */
b,
strong {
  font-weight: bold;
}

/*
 * Address styling not present in Safari 5 and Chrome. */
dfn {
  font-style: italic;
}

/*
 * Address differences between Firefox and other browsers. */
hr {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  height: 0;
}

/*
 * Address styling not present in IE 8/9. */
mark {
  background: yellow;
  color: black;
}

/*
 * Correct font family set oddly in Safari 5 and Chrome. */
code,
kbd,
pre,
samp {
  font-family: monospace, serif;
  font-size: 1em;
}

/*
 * Improve readability of pre-formatted text in all browsers. */
pre {
  white-space: pre-wrap;
}

/*
 * Set consistent quote types. */
q {
  quotes: "“""”""‘""’";
}

/*
 * Address inconsistent and variable font size in all browsers. */
small {
  font-size: 80%;
}

/*
 * Prevent `sub` and `sup` affecting `line-height` in all browsers. */
sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}

sup {
  top: -0.5em;
}

sub {
  bottom: -0.25em;
}

/* ==========================================================================
 * Embedded content
 * ========================================================================== */
/*
 * Remove border when inside `a` element in IE 8/9. */
img {
  border: 0;
}

/*
 * Correct overflow displayed oddly in IE 9. */
svg:not(:root) {
  overflow: hidden;
}

/* ==========================================================================
 * Figures
 * ========================================================================== */
/*
 * Address margin not present in IE 8/9 and Safari 5. */
figure {
  margin: 0;
}

/* ==========================================================================
 * Forms
 * ========================================================================== */
/*
 * Define consistent border, margin, and padding. */
fieldset {
  border: 1px solid silver;
  margin: 0 2px;
  padding: 0.35em 0.625em 0.75em;
}

/*
 * 1. Correct `color` not being inherited in IE 8/9.
 * 2. Remove padding so people aren't caught out if they zero out fieldsets. */
legend {
  border: 0;
  /* 1 */
  padding: 0;
  /* 2 */
}

/*
 * 1. Correct font family not being inherited in all browsers.
 * 2. Correct font size not being inherited in all browsers.
 * 3. Address margins set differently in Firefox 4+, Safari 5, and Chrome. */
button,
input,
select,
textarea {
  font-family: inherit;
  /* 1 */
  font-size: 100%;
  /* 2 */
  margin: 0;
  /* 3 */
}

/*
 * Address Firefox 4+ setting `line-height` on `input` using `!important` in
 * the UA stylesheet. */
button,
input {
  line-height: normal;
}

/*
 * Address inconsistent `text-transform` inheritance for `button` and `select`.
 * All other form control elements do not inherit `text-transform` values.
 * Correct `button` style inheritance in Chrome, Safari 5+, and IE 8+.
 * Correct `select` style inheritance in Firefox 4+ and Opera. */
button,
select {
  text-transform: none;
}

/*
 * 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`
 *    and `video` controls.
 * 2. Correct inability to style clickable `input` types in iOS.
 * 3. Improve usability and consistency of cursor style between image-type
 *    `input` and others. */
button,
html input[type="button"],
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button;
  /* 2 */
  cursor: pointer;
  /* 3 */
}

/*
 * Re-set default cursor for disabled elements. */
button[disabled],
html input[disabled] {
  cursor: default;
}

/*
 * 1. Address box sizing set to `content-box` in IE 8/9/10.
 * 2. Remove excess padding in IE 8/9/10. */
input[type="checkbox"],
input[type="radio"] {
  box-sizing: border-box;
  /* 1 */
  padding: 0;
  /* 2 */
}

/*
 * 1. Address `appearance` set to `searchfield` in Safari 5 and Chrome.
 * 2. Address `box-sizing` set to `border-box` in Safari 5 and Chrome
 *    (include `-moz` to future-proof). */
input[type="search"] {
  -webkit-appearance: textfield;
  /* 1 */
  -moz-box-sizing: content-box;
  -webkit-box-sizing: content-box;
  /* 2 */
  box-sizing: content-box;
}

/*
 * Remove inner padding and search cancel button in Safari 5 and Chrome
 * on OS X. */
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}

/*
 * Remove inner padding and border in Firefox 4+. */
button::-moz-focus-inner,
input::-moz-focus-inner {
  border: 0;
  padding: 0;
}

/*
 * 1. Remove default vertical scrollbar in IE 8/9.
 * 2. Improve readability and alignment in all browsers. */
textarea {
  overflow: auto;
  /* 1 */
  vertical-align: top;
  /* 2 */
}

/* ==========================================================================
 * Tables
 * ========================================================================== */
/*
 * Remove most spacing between table cells. */
table {
  border-collapse: collapse;
  border-spacing: 0;
}

/* ==========================================================================
 * CSS SETTING
 * by Hiroaki WAKATSUKI
 * Converted 2014/2/16
 * ========================================================================== */
*,
*:before,
*:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

img,
object,
embed {
  max-width: 100%;
  height: auto;
}

object,
embed {
  height: 100%;
}

.left {
  float: left;
}

.right {
  float: right;
}

.clearfix {
  *zoom: 1;
}

.clearfix:after {
  content: "\0020";
  display: block;
  height: 0;
  clear: both;
  overflow: hidden;
  visibility: hidden;
}

.text-left {
  text-align: left;
}

.text-right {
  text-align: right;
}

.text-center {
  text-align: center;
}

.text-justify {
  text-align: justify;
}

.hide {
  display: none;
}

.antialiased {
  -webkit-font-smoothing: antialiased;
}

img {
  display: inline-block;
  vertical-align: middle;
}

textarea {
  height: auto;
  min-height: 50px;
}

select {
  width: 100%;
}

i {
  font-style: normal;
}

.animate {
  -moz-transition-property: all;
  -o-transition-property: all;
  -webkit-transition-property: all;
  transition-property: all;
  -moz-transition-duration: 0.2s;
  -o-transition-duration: 0.2s;
  -webkit-transition-duration: 0.2s;
  transition-duration: 0.2s;
  -moz-transition-timing-function: ease-in;
  -o-transition-timing-function: ease-in;
  -webkit-transition-timing-function: ease-in;
  transition-timing-function: ease-in;
}

.button {
  background-image: -moz-linear-gradient(top, rgba(255, 255, 255, 0.05) 1%, rgba(0, 0, 0, 0.2) 100%);
  background-image: -webkit-linear-gradient(top, rgba(255, 255, 255, 0.05) 1%, rgba(0, 0, 0, 0.2) 100%);
  background-image: linear-gradient(to bottom, rgba(255, 255, 255, 0.05) 1%, rgba(0, 0, 0, 0.2) 100%);
}

ul {
  margin: 0;
  padding: 0;
}

ul li {
  list-style: none;
  padding: 0;
  margin: 0;
}

.row {
  width: 100%;
  margin-left: auto;
  margin-right: auto;
  margin-top: 0;
  margin-bottom: 0;
  max-width: 660px;
  *zoom: 1;
}

.row .grid-1,
.row .grid-2,
.row .grid-3,
.row .grid-4,
.row .grid-5,
.row .grid-6,
.row .grid-7,
.row .grid-8,
.row .grid-9,
.row .grid-10,
.row .grid-11,
.row .grid-12 {
  float: left;
  margin-left: 0.9%;
  margin-right: 0.9%;
}

.row .grid-1 {
  width: 6.53333%;
}

.row .grid-2 {
  width: 14.86667%;
}

.row .grid-3 {
  width: 23.2%;
}

.row .grid-4 {
  width: 31.53333%;
}

.row .grid-5 {
  width: 39.86667%;
}

.row .grid-6 {
  width: 48.2%;
}

.row .grid-7 {
  width: 56.53333%;
}

.row .grid-8 {
  width: 64.86667%;
}

.row .grid-9 {
  width: 73.2%;
}

.row .grid-10 {
  width: 81.53333%;
}

.row .grid-11 {
  width: 89.86667%;
}

.row .grid-12 {
  width: 98.2%;
}

.row:before,
.row:after {
  content: " ";
  display: table;
}

.row:after {
  clear: both;
}

.row.collapse>.column,
.row.collapse>.columns {
  position: relative;
  padding-left: 0;
  padding-right: 0;
  float: left;
}

.row.collapse .row {
  margin-left: 0;
  margin-right: 0;
}

.row .row {
  width: auto;
  margin-left: -0.9375em;
  margin-right: -0.9375em;
  margin-top: 0;
  margin-bottom: 0;
  max-width: none;
  *zoom: 1;
}

.row .row:before,
.row .row:after {
  content: " ";
  display: table;
}

.row .row:after {
  clear: both;
}

.row .row.collapse {
  width: auto;
  margin: 0;
  max-width: none;
  *zoom: 1;
}

.row .row.collapse:before,
.row .row.collapse:after {
  content: " ";
  display: table;
}

.row .row.collapse:after {
  clear: both;
}

@media only screen and (max-width: 40em) {

  .row {
    width: 100%;
    padding: 0 20px !important;
  }

  .row .grid-1,
  .row .grid-2,
  .row .grid-3,
  .row .grid-4,
  .row .grid-5,
  .row .grid-6,
  .row .grid-7,
  .row .grid-8,
  .row .grid-9,
  .row .grid-10,
  .row .grid-11,
  .row .grid-12 {
    float: none;
    width: 100% !important;
    margin: 0 !important;
    position: static !important;
  }
}

/* max-width 640px, mobile-only styles, use when QAing mobile issues */
@media only screen and (min-width: 40.063em) and (max-width: 64em) {

  .row .grid-1,
  .row .grid-2,
  .row .grid-3,
  .row .grid-4 {
    width: 48.2% !important;
  }
}

/* min-width 641px and max-width 1024px, use when QAing tablet-only issues */
body,
html {
  height: 100%;
  background-color: #f5f5f3;
}

body {
  padding-top: 60px;
}

h1,
h2,
h3,
h4,
h5,
h6,
body {
  line-height: 1.57;
  letter-spacing: 0.15em;
  font-size: 16px;
  color: #666;
  font-family: 'Unica One', "Avenir", "游ゴシック", "YuGothic", "ヒラギノ角ゴ Pro W6", "HIragino Kaku Gothic Pro W6", "HIragino Kaku Gothic Pro", Osaka, Meiryo, "メイリオ", "ＭＳ Ｐゴシック", "MS P Gothic", sans-serif;
  margin: 0;
}

a {
  text-decoration: none;
  color: #666;
}

a:hover {
  color: #57C3E9;
}

.bold {
  font-weight: bold;
}

.serif,
div.contents.row div.content_post p {
  font-family: 'ほのか明朝', serif;
}

.ultra {
  font-size: 2em !important;
}

::selection {
  background: #D8D8D8;
}

.transition,
a,
form input[type="submit"] {
  -moz-transition-property: all;
  -o-transition-property: all;
  -webkit-transition-property: all;
  transition-property: all;
  -moz-transition-duration: 0.2s;
  -o-transition-duration: 0.2s;
  -webkit-transition-duration: 0.2s;
  transition-duration: 0.2s;
  -moz-transition-timing-function: linear;
  -o-transition-timing-function: linear;
  -webkit-transition-timing-function: linear;
  transition-timing-function: linear;
}

.btn,
header.header div.header__bar.row div.grid-6 a.post {
  padding: 8px 20px;
  font-size: 14px;
  border: 2px solid #57C3E9;
  color: #57C3E9;
  font-weight: bold;
  text-align: center;
  border-radius: 3px;
  display: inline-block;
}

.btn:hover,
header.header div.header__bar.row div.grid-6 a.post:hover {
  border-color: #9bdbf2;
  color: #9bdbf2;
}

.title {
  font-weight: bold;
}

.title--big {
  font-size: 1.5em;
  font-weight: bold;
}

.title--big i {
  font-style: italic;
  font-size: 1.8em;
}

header.header {
  padding: 10px;
  border-bottom: 1px solid #D8D8D8;
  background-color: #fff;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 5;
  height: 62px;
}

header.header div.header__bar.row {
  position: relative;
}

header.header div.header__bar.row h1.grid-6 {
  font-size: 20px;
  line-height: 41px;
  float: left;
}

header.header div.header__bar.row h1.grid-6 a {
  display: block;
}

header.header div.header__bar.row div.grid-6 {
  float: right;
  text-align: right;
}

header.header div.header__bar.row div.grid-6 a.post {
  width: 120px;
  display: inline-left;
  margin-left: 10px;
}

header.header .user_nav {
  position: relative;
  height: 100px;
  right: 0;
}

header.header .user_nav span {
  top: 5px;
  display: block;
  float: left;
  margin-left: 30px;
  width: 150px;
  height: 50px;
  font-size: 1em;
  cursor: pointer;
  position: relative;
}

header.header .user_nav span:after {
  content: '▼';
  font-size: .7em;
  margin-left: -4px;
}

header.header .user_nav span:hover ul {
  color: #57C3E9;
  display: block;
}

header.header .user_nav ul {
  display: none;
  position: absolute;
  top: 46px;
  right: 0;
  border-left: 1px solid #d8d8d8;
  border-right: 1px solid #d8d8d8;
  box-shadow: 1px 2px 5px rgba(0, 0, 0, 0.1);
}

header.header .user_nav ul li {
  background-color: #f0f0f0;
}

header.header .user_nav ul li a {
  display: block;
  padding: 10px 20px;
  text-align: left;
  border-bottom: 1px solid #d8d8d8;
}

.form {
  background: url(https://dl.dropboxusercontent.com/u/5840617/DeathtoStock_Wired3.jpg);
  background-size: cover;
}

.form .contents {
  position: absolute;
  left: 0;
  top: 30%;
  bottom: 0;
  right: 0;
}

.form footer {
  position: absolute;
  bottom: 10px;
  left: 0;
  right: 0;
}

div.contents.row h2 {
  margin: 20px 0;
  padding: 0;
  font-weight: normal;
}

div.contents.row h2 strong {
  font-weight: bold;
  padding-right: 5px;
  font-size: 1.2em;
}

div.contents.row .new_user {
  font-family: "游ゴシック", "YuGothic";
}

div.contents.row div.content_post {
  margin: 20px 0;
  padding: 30px;
  position: relative;
  height: 100%;
  color: #fff;
  background-color: white;
  background-size: cover;
  background-position: center center;
  border-radius: 3px;
  box-shadow: 0 0 10px rgba(41, 41, 41, 0.2);
}

div.contents.row div.content_post .more {
  position: absolute;
  cursor: pointer;
  top: 20px;
  right: 30px;
  z-index: 2;
  height: 30px;
  width: 24px;
  text-align: right;
}

div.contents.row div.content_post .more:hover ul.more_list {
  display: block;
}

div.contents.row div.content_post .more ul.more_list {
  position: absolute;
  text-align: left;
  width: 80px;
  right: 0;
  font-size: 12px;
  background-color: #fff;
  border: 1px solid #ddd;
  display: none;
  box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);
  border-radius: 3px;
}

div.contents.row div.content_post .more ul.more_list li {
  border-bottom: 1px solid #ddd;
}

div.contents.row div.content_post .more ul.more_list li:last-child {
  border-bottom: 0;
}

div.contents.row div.content_post .more ul.more_list li a {
  display: block;
  padding: 5px;
}

div.contents.row div.content_post .more ul.more_list li a:hover {
  background-color: #57C3E9;
  color: #fff;
}

div.contents.row div.content_post p {
  position: absolute;
  left: 30px;
  right: 100px;
  bottom: 30px;
  margin: 0;
  font-size: 20px;
  z-index: 2;
  font-weight: bold;
  text-shadow: 0 0 2px #000, 0 0 1px #000, 0 0 1px #000;
}

div.contents.row div.content_post span.name {
  position: absolute;
  right: 30px;
  bottom: 30px;
  z-index: 2;
  font-size: 13px;
}

div.contents.row div.content_post span.name a {
  display: block;
  color: #aaa;
}

div.contents.row div.content_post span.name a:hover {
  text-decoration: underline;
  color: #aaa;
}

div.contents.row div.content_post span.name span {
  font-size: 9px;
  display: block;
}

div.contents.row .success {
  margin: 20px 0;
  padding: 30px;
  box-shadow: 0 0 10px rgba(41, 41, 41, 0.2);
  background-color: white;
  box-sizing: border-box;
  text-align: center;
}

div.contents.row .success h3 {
  margin: 10px auto;
}

form input,
form textarea {
  width: 100%;
  margin: 5px 0 15px;
  padding: 10px;
  border: 1px solid #D8D8D8;
  border-radius: 5px;
  font-family: "游ゴシック", "YuGothic";
}

form input[type="submit"] {
  background-color: #57C3E9;
  border-radius: 20px;
  color: #fff;
  border: 0;
  font-size: 18px;
}

form input[type="submit"]:hover {
  background-color: #84d3ef;
}

.container {
  margin: 20px 0;
  padding: 30px;
  box-shadow: 0 0 10px rgba(41, 41, 41, 0.2);
  background-color: white;
  box-sizing: border-box;
}

.container h3 {
  margin: 0 0 20px;
  text-align: center;
  font-weight: normal;
  font-size: 20px;
  color: #666;
}

.comments {
  padding: 5px;
  margin-top: 15px;
}

.comments a {
  color: #57C3E9;
}

.comments a:hover {
  text-decoration: underline;
}

footer {
  margin: 30px auto;
  padding: 10px;
  color: #D8D8D8;
}

footer p {
  text-align: center;
}

.search-form {
  text-align: center;
  padding-top: 32px;
}

.search-form .search-input {
  width: 30%;
  margin-right: 10px;
}

.search-form .search-btn {
  width: 10%;
}

.tweet_text{
  color: #000;
  font-size: 24px;
  margin-top: 15px;
  white-space:normal;
}
```
